config/routes.rb
Rails.application.routes.draw do
  root 'apartments#index'
  resources :apartments
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  
  def index

    searched_param = params[:search]

    if !searched_param.nil? and (searched_param[2..5] == "room" or searched_param[2..5] == "Room" or searched_param[1..4] == "room" or searched_param[1..4] == "Room")
      @apartments = Apartment.where("Number_of_Rooms LIKE ?","%#{searched_param[0]}%")
    elsif !searched_param.nil? and (searched_param[2..5] == "bath" or searched_param[2..5] == "Bath" or searched_param[1..4] == "bath" or searched_param[1..4] == "Bath")
      @apartments = Apartment.where("Number_of_Bathrooms LIKE ?","%#{searched_param[0]}%")
    else 
    @apartments = Apartment.where("Destination LIKE ?","%#{searched_param}%")
    end

    
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:Destination, :Owner_Name, :Mobile_Number, :URL, :Number_of_Rooms, :Number_of_Bathrooms)
    end


end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Destination %>
    <%= form.text_field :Destination %>
  </div>

  <div class="field">
    <%= form.label :Owner_Name %>
    <%= form.text_field :Owner_Name %>
  </div>

  <div class="field">
    <%= form.label :Mobile_Number %>
    <%= form.text_field :Mobile_Number %>
  </div>

  <div class="field">
    <%= form.label :URL %>
    <%= form.text_field :URL %>
  </div>

  <div class="field">
    <%= form.label :Number_of_Rooms %>
    <%= form.number_field :Number_of_Rooms %>
  </div>

  <div class="field">
    <%= form.label :Number_of_Bathrooms %>
    <%= form.number_field :Number_of_Bathrooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<%# Logo %>
<%= image_tag("logo.jpg", width: 50, height: 50, :alt => "logo feed") %>

<%# Heading %>
<h1>Apartments</h1>

<%# Login %>
<%= link_to 'sign in',  new_user_registration_path, method: :get %>

<%# Logout %>
<%= link_to 'sign out',  destroy_user_session_path, method: :delete %>

<%# Search %>
<%= form_tag apartments_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>


<%# Database Table %>
<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Owner name</th>
      <th>Mobile number</th>
      <th>Url</th>
      <th>Number of rooms</th>
      <th>Number of bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><center><%= apartment.Destination %></td>
        <td><center><%= apartment.Owner_Name %></td>
        <td><center><%= apartment.Mobile_Number %></td>
        <td><center><%= link_to(apartment.URL ,"https://yallasa7el.com/rooms/"+apartment.URL, target: "_blank") %></td>
        <td><center><%= apartment.Number_of_Rooms %></td>
        <td><center><%= apartment.Number_of_Bathrooms %></td>
        <td><center><%= link_to 'Show', apartment %></td>
        <td><center><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><center><%= image_tag(apartment.URL+".jpg", width: 136, height: 67, :alt => apartment.URL+" feed") %></td>>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# Creating new apartment %>
<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Destination:</strong>
  <%= @apartment.Destination %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @apartment.Owner_Name %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @apartment.Mobile_Number %>
</p>

<p>
  <strong>Url:</strong>
  <%= @apartment.URL %>
</p>

<p>
  <strong>Number of rooms:</strong>
  <%= @apartment.Number_of_Rooms %>
</p>

<p>
  <strong>Number of bathrooms:</strong>
  <%= @apartment.Number_of_Bathrooms %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>